#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyTimeTracker.Android.Resource", IsApplication=true)]

namespace MyTimeTracker.Android
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int WhiteOpaque = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Splash = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int SplashBackground = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Start = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Stop = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070003
			public const int ConnectionTestButton = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int DomainEditText = 2131165184;
			
			// aapt resource value: 0x7f07000c
			public const int EmptyIssueListTextView = 2131165196;
			
			// aapt resource value: 0x7f070005
			public const int IssueIdTextView = 2131165189;
			
			// aapt resource value: 0x7f070007
			public const int IssueTitleTextView = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int IssueTrackingTableLayout = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int IssueTrackingTextView = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int MyIssuesListView = 2131165195;
			
			// aapt resource value: 0x7f070002
			public const int PasswordEditText = 2131165186;
			
			// aapt resource value: 0x7f070004
			public const int SaveButton = 2131165188;
			
			// aapt resource value: 0x7f07000a
			public const int StopTrackingImageButton = 2131165194;
			
			// aapt resource value: 0x7f070006
			public const int TotalTextView = 2131165190;
			
			// aapt resource value: 0x7f070001
			public const int UserEditText = 2131165185;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ConfigurationView = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int IssueRowView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MyIssuesView = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int ApplicationName = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int ConnectionTestButton = 2131034122;
			
			// aapt resource value: 0x7f05000c
			public const int ConnectionTestFailedMessage = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int ConnectionTestSucceedMessage = 2131034123;
			
			// aapt resource value: 0x7f050006
			public const int DomainTextView = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int IssueTrackingMessage = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int NoIssuesAvailableMessage = 2131034115;
			
			// aapt resource value: 0x7f050008
			public const int PasswordTextView = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int SaveButton = 2131034121;
			
			// aapt resource value: 0x7f050001
			public const int SelectIssueToTrackMessage = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int UserTextView = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int WorklogSavedMessage = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int WorklogTrackingStartedMessage = 2131034117;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int SplashTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
